development:
  adapter: postgresql
  encoding: unicode
  database: subz_development  #name is name of app _development 
  pool: 5
  host: localhost
  username: postgres
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: subz_production  #name is name of app _development 
  pool: 5
  host: localhost
  username: postgres
  password: 1234