development:
  adapter: postgresql
  encoding: unicode
  database: energies_development
  pool: 5
  host: localhost
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: energies_production 
  pool: 5
  host: localhost
  username: postgres
  password: ยง
